let
    aportes_colectivoscd = let
    Source = Excel.Workbook(File.Contents("C:\Users\godoyd\Downloads\aportes_colectivoscd.xlsx"), null, true),
    aportes_colectivoscd_Sheet = Source{[Item="aportes_colectivoscd",Kind="Sheet"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(aportes_colectivoscd_Sheet,{{"Column1", type text}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Column1", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Column1.1", "Column1.2", "Column1.3", "Column1.4", "Column1.5", "Column1.6"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column1.1", type text}, {"Column1.2", type text}, {"Column1.3", type text}, {"Column1.4", type text}, {"Column1.5", type text}, {"Column1.6", type text}}),
   //Remombro Columnas con numero por palabras para que sean descriptivas
    #"MiTransformacionManual" = Table.RenameColumns(#"Changed Type1",{{"Column1.1", "Mes"}, {"Column1.2", "CUIT"}, {"Column1.3", "Provincia"}, {"Column1.4", "Municipio"}, {"Column1.5", "Monto"}, {"Column1.6", "Tipo"}}),
    #"Removed Top Rows" = Table.Skip(#"Renamed Columns",1),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Top Rows",{{"Mes", type date}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each ([Provincia] = "BUENOS AIRES"))
in
    #"MiTransformacionManual",
    #"Promoted Headers" = Table.PromoteHeaders(aportes_colectivoscd, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"mes", type date}, {"cuit", type text}, {"provincia", type text}, {"municipio", type text}, {"monto", Int64.Type}, {"tipo", type text}})
in
    #"Changed Type"

### ¿Por qué es útil para un analista de datos entender la estructura `let … in`?

Entender la estructura `let … in` es útil porque permite comprender cómo Power Query organiza y ejecuta las transformaciones de los datos. Dentro de `let` se definen los distintos pasos de la consulta y cada paso puede utilizar como entrada el resultado del paso anterior. Por su parte, `in` indica cuál de esos pasos será devuelto como resultado final.

Para un analista de datos, comprender esta estructura facilita la lectura del código generado automáticamente, la detección de errores y la modificación manual de transformaciones sin depender exclusivamente de la interfaz gráfica de Power Query.

### ¿Qué significa que el lenguaje M sea Case Sensitive y cuál es la consecuencia práctica de ignorarlo?

Que el lenguaje M sea **Case Sensitive** significa que distingue entre letras mayúsculas y minúsculas. Por lo tanto, los nombres de funciones, variables y pasos deben escribirse exactamente como fueron definidos.

Por ejemplo, `Table.SelectRows` y `table.selectrows` no son equivalentes. La primera expresión corresponde a una función válida de M, mientras que la segunda puede producir un error.

La consecuencia práctica de ignorar esta característica es que una consulta puede dejar de ejecutarse correctamente por un simple cambio entre mayúsculas y minúsculas. Por eso, al modificar código en el Editor Avanzado es importante respetar exactamente la sintaxis y los nombres utilizados.

### ¿Por qué elegiste ese dataset y qué criterios usaste para seleccionarlo?

Elegí este dataset de transporte porque su estructura permite practicar de manera clara las transformaciones solicitadas en el ejercicio. Contiene más de cinco columnas y diferentes tipos de datos, incluyendo texto, números enteros, provincia y fechas.

Los principales criterios utilizados para seleccionarlo fueron la variedad de tipos de datos, la cantidad de columnas, la presencia de nombres técnicos y la posibilidad de realizar transformaciones representativas de un proceso de preparación de datos en Power Query.
